# Generated by Django 5.1.1 on 2024-09-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150, verbose_name='Слаг')),
                ('title', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': ('Вид услуг',),
                'verbose_name_plural': 'Виды услуг',
            },
        ),
    ]
