# Generated by Django 5.1 on 2024-09-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alev', '0004_category_h1_category_h1_p_category_h2_category_h2_p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='h1_span',
            field=models.TextField(blank=True, null=True),
        ),
    ]
