# Generated by Django 5.1 on 2024-09-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alev', '0005_category_h1_span'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='h1_after_span',
            field=models.TextField(blank=True, null=True),
        ),
    ]
