# Generated by Django 5.1 on 2024-09-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alev', '0006_category_h1_after_span'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='h2_p2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
