# Generated by Django 5.1 on 2024-09-12 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alev', '0007_category_h2_p2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_object', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name': ('Объект',),
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='object')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alev.objects')),
            ],
            options={
                'verbose_name': ('Фото',),
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
