# Generated by Django 5.1 on 2024-09-12 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alev', '0008_objects_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': ('Поверхность',),
                'verbose_name_plural': 'Поверхность',
            },
        ),
        migrations.CreateModel(
            name='Type_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': ('Вид работ',),
                'verbose_name_plural': 'Виды работ',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Наименование работ')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('surface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alev.surface')),
                ('type_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alev.type_work')),
            ],
            options={
                'verbose_name': ('Прайс',),
                'verbose_name_plural': 'Прайс',
            },
        ),
    ]
