# Generated by Django 5.1 on 2024-09-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alev', '0009_surface_type_work_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='remont',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
