# Generated by Django 5.1 on 2024-09-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alev', '0010_remont_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartira',
            name='img',
            field=models.TextField(null=True),
        ),
    ]
