# Generated by Django 5.1 on 2024-09-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alev', '0012_remont_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remont',
            old_name='title',
            new_name='title_h2',
        ),
        migrations.AddField(
            model_name='remont',
            name='h1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remont',
            name='h1_after_span',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remont',
            name='h1_p',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remont',
            name='h1_span',
            field=models.TextField(blank=True, null=True),
        ),
    ]
