# Generated by Django 5.1 on 2024-09-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alev', '0013_rename_title_remont_title_h2_remont_h1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=50)),
                ('repair_type', models.CharField(max_length=50)),
                ('room_count', models.CharField(max_length=50)),
                ('area', models.FloatField()),
                ('design_project', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': ('Калькулятор',),
                'verbose_name_plural': 'Калькулятор',
            },
        ),
    ]
