# Generated by Django 5.1 on 2024-09-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alev', '0014_calculationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': ('Обратная связь',),
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
