# Generated by Django 5.1 on 2024-09-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alev', '0015_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
